db.url=jdbc:postgresql://localhost:5432/pokedecks
db.user=docker
db.password=docker

# JWT Configuration
jwt.secret=MGQicn6bDVZXFsBi1VXoRHt40PLYkkR4xgJwWc6AzyiNrWQKBikdhtUxXmpebF6g1rKNqHn/7YKF9qLHk0WTlA==
jwt.expiration=86400000
